version: "3.9"

services:
  postgres:
    image: postgres:9.5.25-alpine
    ports:
      - 5442:5432
    volumes:
      - type: volume
        source: postgres
        target: /var/lib/postgresql/data
    environment:
      - TZ=Asia/Tokyo
      - POSTGRES_DB=crud-pgsql
      - POSTGRES_PASSWORD=secret

volumes:
  postgres: